/*
 * Artemidos - build configuration
 * GENERATED by scripts/build-flavour.js. Do not edit, do not commit.
 *
 * Flavour: keyed   Written: 2026-08-10
 */
window.ART_BUILD = {
  flavour: "keyed",
  requiresKey: true,
  licencePublicKey: {"kty":"EC","x":"NXRncbFG69penglx7QhJWhJ8KrTnokUJXtPOd9d4UIw","y":"azjW531lOo0n3T28uKgR5LcgzRxH7deXFvQgMe-IVrk","crv":"P-256"}
};
